import { AlumniInformation } from '../types/types';

export const ALUMNI: Array<AlumniInformation> = [
  {
    Alumni_ID: 1,
    Name: 'Chang Gao',
    Post_SAIL: 'University of Virginia & Microsoft',
    SAIL_Position: 'Software Engineer Intern',
  },
  {
    Alumni_ID: 2,
    Name: 'Aditi Dass',
    Post_SAIL: 'State Street',
    SAIL_Position: 'Software Engineer Intern',
  },
  {
    Alumni_ID: 3,
    Name: 'Ben Getchell',
    Post_SAIL: 'Software & Application Innovation Lab, Nth Party, Ltd.',
    SAIL_Position: 'Software Engineer Intern, Software Engineer',
  },
  {
    Alumni_ID: 4,
    Name: 'Ekaterina Propokeva',
    Post_SAIL: 'Amazon Web Services',
    SAIL_Position: 'Software Engineer Intern',
  },
  {
    Alumni_ID: 5,
    Name: 'David Wang',
    Post_SAIL: 'Amazon',
    SAIL_Position: 'Software Engineer Intern',
  },
  {
    Alumni_ID: 6,
    Name: 'Jacqueline You',
    Post_SAIL: 'Boston University School of Medicine',
    SAIL_Position: 'Software Engineer Intern',
  },
  {
    Alumni_ID: 7,
    Name: 'Raphael Baysa',
    Post_SAIL: 'Pixel Machinery',
    SAIL_Position: 'Software Engineer Intern',
  },
  {
    Alumni_ID: 8,
    Name: 'Anna Goncharova',
    Post_SAIL: 'Twitter',
    SAIL_Position: 'Software Engineer Intern',
  },
  {
    Alumni_ID: 9,
    Name: 'Tim Lim',
    Post_SAIL: 'Google',
    SAIL_Position: 'Software Engineer Intern',
  },
  {
    Alumni_ID: 10,
    Name: 'Johnson Lam',
    Post_SAIL: 'Soroco',
    SAIL_Position: 'Software Engineer Intern',
  },
  {
    Alumni_ID: 11,
    Name: 'Ibrahim Shaikh',
    Post_SAIL: 'ITG',
    SAIL_Position: 'Software Engineer Intern',
  },
  {
    Alumni_ID: 12,
    Name: 'Linlan Chen',
    Post_SAIL: 'Facebook',
    SAIL_Position: 'Software Engineer Intern',
  },
  {
    Alumni_ID: 13,
    Name: 'Sreeja Keesara',
    Post_SAIL: 'Goldman Sachs',
    SAIL_Position: 'Software Engineer Intern',
  },
  {
    Alumni_ID: 14,
    Name: 'Rudhra Raveendran',
    Post_SAIL: 'Microsoft',
    SAIL_Position: 'Software Engineer Intern',
  },
  {
    Alumni_ID: 15,
    Name: 'Ryan Walsh',
    Post_SAIL: 'HubSpot',
    SAIL_Position: 'Software Engineer Intern',
  },
  {
    Alumni_ID: 16,
    Name: 'Justin Chen',
    Post_SAIL: 'Systems & Technology Research',
    SAIL_Position: 'Software Engineer Intern',
  },
  {
    Alumni_ID: 17,
    Name: 'Kinan Dak Albab',
    Post_SAIL: 'Ph.D. Student at Brown University',
    SAIL_Position: 'Software Engineer Intern',
  },
  {
    Alumni_ID: 18,
    Name: 'Chen Garber',
    Post_SAIL: 'Facebook',
    SAIL_Position: 'Software Engineer Intern',
  },
  {
    Alumni_ID: 19,
    Name: 'Qian Mei',
    Post_SAIL: 'Growald Family Fund',
    SAIL_Position: 'Software Engineer Intern',
  },
  {
    Alumni_ID: 20,
    Name: 'Rawane Issa',
    Post_SAIL: 'Ph.D. Student at Boston University',
    SAIL_Position: 'Software Engineer Intern',
  },
  {
    Alumni_ID: 21,
    Name: 'Daniel Valentine',
    Post_SAIL: '',
    SAIL_Position: 'Software Engineer Intern',
  },
  {
    Alumni_ID: 22,
    Name: 'Esen Harris',
    Post_SAIL: 'Accenture',
    SAIL_Position: 'Software Engineer Intern',
  },
  {
    Alumni_ID: 23,
    Name: 'Anya Gilad',
    Post_SAIL: 'AthenaHealth',
    SAIL_Position: 'Software Engineer Intern',
  },
  {
    Alumni_ID: 27,
    Name: 'Stephanie Gomez',
    Post_SAIL: 'Luminopia',
    SAIL_Position: 'Software Engineer Intern',
  },
  {
    Alumni_ID: 28,
    Name: 'Peter Flockhart',
    Post_SAIL: 'Software & Application Innovation Lab, Starry Internet',
    SAIL_Position: 'Software Engineer Intern, Software Engineer',
  },
  {
    Alumni_ID: 29,
    Name: 'Glenn Liem',
    Post_SAIL: '',
    SAIL_Position: 'Software Engineer Intern',
  },
  {
    Alumni_ID: 30,
    Name: 'Rachel Manzelli',
    Post_SAIL: 'Modulate.ai',
    SAIL_Position: 'Software Engineer Intern',
  },
  {
    Alumni_ID: 31,
    Name: 'Francis Zamora',
    Post_SAIL: 'Twilio',
    SAIL_Position: 'Software Engineer Intern',
  },
  {
    Alumni_ID: 32,
    Name: 'Nicolas Alhaddad',
    Post_SAIL: 'Ph.D. Student at Boston University',
    SAIL_Position: 'Software Engineer Intern',
  },
  {
    Alumni_ID: 33,
    Name: 'Yiwen Gu',
    Post_SAIL: 'Ph.D. Student',
    SAIL_Position: 'Software Engineer Intern',
  },
  {
    Alumni_ID: 34,
    Name: 'Sidhartha Premkumar',
    Post_SAIL: '',
    SAIL_Position: 'Software Engineer Intern',
  },
  {
    Alumni_ID: 35,
    Name: 'David Shen',
    Post_SAIL: '',
    SAIL_Position: 'Software Engineer Intern',
  },
  {
    Alumni_ID: 36,
    Name: 'Megan Fantes',
    Post_SAIL: 'iRobot',
    SAIL_Position: 'Software Engineer Intern',
  },
  {
    Alumni_ID: 37,
    Name: 'Usama Ahsan',
    Post_SAIL: '',
    SAIL_Position: 'Software Engineer Intern',
  },
  {
    Alumni_ID: 38,
    Name: 'Efstathios Karatsiolis',
    Post_SAIL: '',
    SAIL_Position: 'Software Engineer Intern',
  },
  {
    Alumni_ID: 39,
    Name: 'FanonX Rogers',
    Post_SAIL: 'Oracle',
    SAIL_Position: 'Software Engineer Intern',
  },
  {
    Alumni_ID: 40,
    Name: 'Ashni Shah',
    Post_SAIL: '',
    SAIL_Position: 'Software Engineer Intern',
  },
  {
    Alumni_ID: 41,
    Name: 'Christopher Trinh',
    Post_SAIL: '',
    SAIL_Position: 'Software Engineer Intern',
  },
  {
    Alumni_ID: 42,
    Name: 'Yi (Zack) Zhang',
    Post_SAIL: '',
    SAIL_Position: 'Software Engineer Intern',
  },
  {
    Alumni_ID: 43,
    Name: 'Marcella Hastings',
    Post_SAIL: '',
    SAIL_Position: 'Software Engineer Intern',
  },
  {
    Alumni_ID: 44,
    Name: 'Tanner Braun',
    Post_SAIL: 'Nth Party, Ltd.',
    SAIL_Position: 'Software Engineer Intern',
  },
  {
    Alumni_ID: 45,
    Name: 'Gagandeep Kang',
    Post_SAIL: 'Amazon',
    SAIL_Position: 'Software Engineer Intern',
  },
  {
    Alumni_ID: 46,
    Name: 'Ruizhi Jiang',
    Post_SAIL: '',
    SAIL_Position: 'Software Engineer Intern',
  },
  {
    Alumni_ID: 47,
    Name: 'Yuwan Xiao',
    Post_SAIL: '',
    SAIL_Position: 'Software Engineer Intern',
  },
  {
    Alumni_ID: 48,
    Name: 'Xuan Hy Nguyen',
    Post_SAIL: '',
    SAIL_Position: 'Software Engineer Intern',
  },
  {
    Alumni_ID: 49,
    Name: 'Raj Vipani',
    Post_SAIL: 'Galatea Associates',
    SAIL_Position: 'Software Engineer Intern',
  },
  {
    Alumni_ID: 50,
    Name: 'Taesung Yoon',
    Post_SAIL: '',
    SAIL_Position: 'Software Engineer Intern',
  },
  {
    Alumni_ID: 51,
    Name: 'Christopher Cho',
    Post_SAIL: '',
    SAIL_Position: 'Software Engineer Intern',
  },
  {
    Alumni_ID: 52,
    Name: 'Nicholas Goutermout',
    Post_SAIL: 'Keystone Strategy',
    SAIL_Position: 'Software Engineer Intern',
  },
  {
    Alumni_ID: 53,
    Name: 'Nicholas Hall',
    Post_SAIL: '',
    SAIL_Position: 'Software Engineer Intern',
  },
  {
    Alumni_ID: 54,
    Name: 'Ammar Ahmad',
    Post_SAIL: '',
    SAIL_Position: 'Software Engineer Intern',
  },
  {
    Alumni_ID: 55,
    Name: 'Lucy Qin',
    Post_SAIL: 'Ph.D. Student at Brown University',
    SAIL_Position: 'Software Engineer',
  },
  {
    Alumni_ID: 56,
    Name: 'Ira Globus-Harris',
    Post_SAIL: '',
    SAIL_Position: 'Software Engineer',
  },
  {
    Alumni_ID: 57,
    Name: 'Shreya Pandit',
    Post_SAIL: '',
    SAIL_Position: 'Software Engineer',
  },
  {
    Alumni_ID: 58,
    Name: 'Sarah Leinicke',
    Post_SAIL: 'Harvard University',
    SAIL_Position: 'Software Engineer',
  },
  {
    Alumni_ID: 59,
    Name: 'Greg Frasco',
    Post_SAIL: '',
    SAIL_Position: 'Software Engineer',
  },
  {
    Alumni_ID: 60,
    Name: 'Frederick Jansen',
    Post_SAIL: 'Nth Party, Ltd.',
    SAIL_Position: 'Associate Director of Engineering',
  },
  {
    Alumni_ID: 61,
    Name: 'Dany Fu',
    Post_SAIL: 'Editas Medicine',
    SAIL_Position: 'Senior Software Engineer',
  },
];
