name: Deploy
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Set up Node.js 16'
        uses: actions/setup-node@v2.4.1
        with:
          node-version: 16
      - name: Checkout
        uses: actions/checkout@v2.3.1
      - name: Build
        run: |
          npm install
          npm run build
      - name: Deploy to gh-pages branch
        if: github.event_name == 'push'
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: .
